tof.obj : error LNK2019: "void __cdecl cv::imshow(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class cv::debug_build_guard::_InputArray const &)" (?imshow@cv@@YAXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV_InputArray@debug_build_guard@1@@Z)__catch$_main$0 함수에서 참조되는 확인할 수 없는 외부 기호
tof.obj : error LNK2019: "public: __thiscall serial::Serial::Serial(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned int,struct serial::Timeout,enum serial::bytesize_t,enum serial::parity_t,enum serial::stopbits_t,enum serial::flowcontrol_t)" (??0Serial@serial@@QAE@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@IUTimeout@1@W4bytesize_t@1@W4parity_t@1@W4stopbits_t@1@W4flowcontrol_t@1@@Z)"void __cdecl `dynamic initializer for 'Serial''(void)" (??__ESerial@@YAXXZ) 함수에서 참조되는 확인할 수 없는 외부 기호
tof.obj : error LNK2019: "public: virtual __thiscall serial::Serial::~Serial(void)" (??1Serial@serial@@UAE@XZ)"void __cdecl `dynamic atexit destructor for 'Serial''(void)" (??__FSerial@@YAXXZ) 함수에서 참조되는 확인할 수 없는 외부 기호
tof.obj : error LNK2019: "public: bool __thiscall serial::Serial::isOpen(void)const " (?isOpen@Serial@serial@@QBE_NXZ)_main 함수에서 참조되는 확인할 수 없는 외부 기호
tof.obj : error LNK2019: "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall serial::Serial::read(unsigned int)" (?read@Serial@serial@@QAE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@I@Z)_main 함수에서 참조되는 확인할 수 없는 외부 기호
tof.obj : error LNK2019: "public: unsigned int __thiscall serial::Serial::write(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?write@Serial@serial@@QAEIABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)_main 함수에서 참조되는 확인할 수 없는 외부 기호
C:\opencv\build\x64\vc15\lib\opencv_world460d.lib : warning LNK4272: 'x64' 라이브러리 컴퓨터 종류가 'x86' 대상 컴퓨터 종류와 충돌합니다.
C:\Users\user\Desktop\TOF\Debug\TOF.exe : fatal error LNK1120: 6개의 확인할 수 없는 외부 참조입니다.
